pizzamamadjango/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name="index"),
]

pizzamamadjango/menu/urls.py
from django.urls import path

from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name="index"),
]

pizzamamadjango/pizzamamadjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('main.urls'))
]

pizzamamadjango/main/models.py
from django.db import models

# Create your models here.

pizzamamadjango/menu/models.py
from django.db import models

class Pizza(models.Model):
    name = models.CharField(max_length=100)
    ingredients = models.CharField(max_length=100)
    price = models.FloatField(default=0)
    vegetarian = models.BooleanField(default=False)

    def __str__(self):
        return self.name

pizzamamadjango/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):


    return  render(request, "main/index.html")

pizzamamadjango/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza
# Create your views here.

def index(request):
    # pizzas = Pizza.objects.all()
    # pizzas_names_and_prices = [pizza.name +" : " + str(pizza.price) for pizza in pizzas]
    # pizza_str = ", ".join(pizzas_names_and_prices)
    #
    #
    # return HttpResponse(pizza_str)
    pizzas = Pizza.objects.all().order_by('price')
    return render(request, "menu/index.html", {"pizzas":pizzas})

pizzamamadjango/main/templates/main/index.html
{% load static %}

<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div  class="centered">

    <img src="{% static 'main/images/main_logo.png' %}" alt="logo">
    <a href="{% url 'menu:index' %}">See our Menu</a>
        </div>

</body>
</html>

pizzamamadjango/menu/templates/menu/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Our Pizza</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
<!--logo-->
<a href="{% url 'main:index' %}"><img src="{% static 'menu/images/small_logo.png' %}" alt="the logo of the page" id="logo"></a>
<div class="menu_title">
<h1>Our Pizza</h1>
</div>

<div class="menu_list">
{%for pizza in pizzas %}

    <div class="menu_list_items">

       <span class="menu_list_title"> {{pizza.name}} </span>
        <span class="menu_list_price"> {{pizza.price}} $</span>
        <span class="menu_list_ingredients"> {{pizza.ingredients}} </span>
        {% if pizza.vegetarian %}
         <span class="menu_vegetarian"> VEGETARIAN </span>
        {%endif%}

    </div>

{% endfor %}
</div>


</body>
</html>